---
title: "Texas Covid Data Project"
author: "Nathen Byford, Connor Bryson, Miguel Iglesias"
date: "11/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library("lubridate")
library("slider")
library("tidyverse")
theme_set(
    theme_classic() +
        theme(panel.grid.major.y = element_line(),
              axis.title.y = element_text(angle = 0, vjust = .5),
              plot.title = element_text(face = "bold"),
              legend.text = element_text(size = 8)
              )
        )
```

# Part 1: Data manipulation

```{r}
tb <- read_xlsx(".\\data\\data.xlsx", skip = 2)

cases <- tb |> 
  rename(county = "County Name") |> 
  gather(-1, key = "date", value = "cases") |> 
  mutate(date = str_extract(date, "[0-9]{2}-[0-9]{2}-[0-9]{4}"),
         date = mdy(date))

cases
```

# Part 2: Data merging

```{r}
pop_dat <- read_csv(".\\data/county-populations.csv")

cases <- left_join(cases, pop_dat)

cases
```

# part 3: Data visualization

```{r, fig.align='center', fig.height=4}
# Find top 16 counties, and total.
top_count <- tail(pop_dat[order(pop_dat$population), ], n = 17) |> pull(county)

cases |> filter(county %in% top_count, county != "Total") |> 
  group_by(county) |> 
  mutate(new_cases = c(cases[1], diff(cases)),
         new_cases = slide_dbl(new_cases, mean, .before = 6)) |> 
  ggplot(aes(x = date, y = new_cases, group = county)) +
  geom_line(aes(color = county), size = .7, alpha = .6) +
  scale_y_continuous(labels = scales::comma, limits = c(0, NA)) +
  scale_color_viridis_d() +
  labs(title = "Incident Cases", 
       subtitle = "For 16 Largest Counties in Texas",
       y = "Cases",
       x = "Date")
```

# Part 4: Facet Graphics

```{r}
cases |> filter(county %in% top_count, county != "Total") |> 
  group_by(county) |> 
  mutate(new_cases = c(cases[1], diff(cases)),
         new_cases = slide_dbl(new_cases, mean, .before = 6)) |> 
  ggplot(aes(x = date, y = new_cases, group = county)) +
  geom_line(size = 0.7, alpha = .6) +
  scale_y_continuous(labels = scales::comma, limits = c(0,NA)) +
  labs(title = "Incident Cases", 
       subtitle = "For 16 Largest Counties in Texas", 
       x = "Date",
       y = "New Cases") +
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1),
        strip.text = element_text(size = 6))+
  facet_wrap(~county, nrow = 4)


```

#Part 5: Cases per 10k

```{r}
cases |> filter(county %in% top_count, county != "Total") |> 
  group_by(county) |> 
  mutate(new_cases = c(cases[1], diff(cases)),
         new_cases = slide_dbl(new_cases, mean, .before = 6),
         cases_10k = (new_cases/population)*1e5) |> 
  ggplot(aes(x = date, y = cases_10k, group = county)) +
  geom_line(aes(color = county), size = .7, alpha = .6) +
  scale_y_continuous(labels = scales::comma, limits = c(0, NA)) +
  scale_color_viridis_d() +
  labs(title = "Cases per 10k", 
       subtitle = "For 16 Largest Counties in Texas",
       y = "Cases per 10k",
       x = "Date")
```

```{r}
cases |> filter(county %in% top_count, county != "Total") |> 
  group_by(county) |> 
  mutate(new_cases = c(cases[1], diff(cases)),
         new_cases = slide_dbl(new_cases, mean, .before = 6),
         cases_10k = (new_cases/population)*1e5) |> 
  ggplot(aes(x = date, y = cases_10k, group = county)) +
  geom_line(size = 0.7, alpha = .6) +
  scale_y_continuous(labels = scales::comma, limits = c(0,NA)) +
  labs(title = "Cases Per 10k", 
       subtitle = "For 16 Largest Counties in Texas", 
       x = "Date",
       y = "Cases per 10k") +
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1),
        strip.text = element_text(size = 6))+
  facet_wrap(~county, nrow = 4)
```



